"""add_telemetry_locations

Revision ID: 1273ba2cc8fb
Revises: 79b4ec72ad65
Create Date: 2026-04-14 00:55:38.579450
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1273ba2cc8fb'
down_revision: str | None = '79b4ec72ad65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wrappers_fdw_stats',
    sa.Column('fdw_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('create_times', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total number of times the FDW instacne has been created'),
    sa.Column('rows_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows input from origin'),
    sa.Column('rows_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows output to Postgres'),
    sa.Column('bytes_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes input from origin'),
    sa.Column('bytes_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes output to Postgres'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Metadata specific for the FDW'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fdw_name', name=op.f('wrappers_fdw_stats_pkey')),
    comment='Wrappers Foreign Data Wrapper statistics'
    )
    op.drop_index(op.f('ix_vehicle_locations_vehicle_id'), table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    # ### end Alembic commands ###
