"""add_compliance_boardings

Revision ID: 79b4ec72ad65
Revises: b378061eb2f0
Create Date: 2026-04-14 00:51:27.158537
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b4ec72ad65'
down_revision: str | None = 'b378061eb2f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('boarded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardings_booking_id'), 'boardings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_boardings_driver_id'), 'boardings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_boardings_stop_id'), 'boardings', ['stop_id'], unique=False)
    op.create_index(op.f('ix_boardings_vehicle_id'), 'boardings', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boardings_vehicle_id'), table_name='boardings')
    op.drop_index(op.f('ix_boardings_stop_id'), table_name='boardings')
    op.drop_index(op.f('ix_boardings_driver_id'), table_name='boardings')
    op.drop_index(op.f('ix_boardings_booking_id'), table_name='boardings')
    op.drop_table('boardings')
    # ### end Alembic commands ###
