"""harden_trips_and_routes

Revision ID: b378061eb2f0
Revises: 95b0c3305cc9
Create Date: 2026-04-14 00:42:02.335935
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b378061eb2f0'
down_revision: str | None = '95b0c3305cc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('qr_tokens_booking_id_key'), 'qr_tokens', type_='unique')
    op.drop_index(op.f('ix_qr_tokens_booking_id'), table_name='qr_tokens')
    op.create_index(op.f('ix_qr_tokens_booking_id'), 'qr_tokens', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_tokens_booking_id'), table_name='qr_tokens')
    op.create_index(op.f('ix_qr_tokens_booking_id'), 'qr_tokens', ['booking_id'], unique=False)
    op.create_unique_constraint(op.f('qr_tokens_booking_id_key'), 'qr_tokens', ['booking_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
